#!/usr/bin/env python3
"""
Build Script for AutoGrader System

This script builds distributable executables for:
1. AssignmentEditor - For instructors to create/edit assignments
2. AutoGrader - For students to check their code

Usage:
    python build_executables.py [options]

Options:
    --editor    Build only the Assignment Editor
    --grader    Build only the AutoGrader (student app)
    --all       Build both (default)
    --clean     Clean build folders before building
    --debug     Build with console window for debugging

Prerequisites:
    pip install pyinstaller pandas openpyxl numpy matplotlib reportlab
"""

import subprocess
import sys
import os
import shutil
import argparse


def run_command(cmd, description):
    """Run a command and handle errors."""
    print(f"\n{'='*60}")
    print(f"  {description}")
    print(f"{'='*60}")
    print(f"Running: {' '.join(cmd)}\n")
    
    result = subprocess.run(cmd, capture_output=False)
    
    if result.returncode != 0:
        print(f"\n✗ FAILED: {description}")
        return False
    
    print(f"\n✓ SUCCESS: {description}")
    return True


def check_prerequisites():
    """Check if required packages are installed."""
    # Map of package names to their importable module names
    required = {
        'pyinstaller': 'PyInstaller',  # PyInstaller uses capital letters
        'pandas': 'pandas',
        'openpyxl': 'openpyxl',
    }
    missing = []
    
    for pkg_name, import_name in required.items():
        try:
            __import__(import_name)
        except ImportError:
            missing.append(pkg_name)
    
    if missing:
        print("✗ Missing required packages:")
        for pkg in missing:
            print(f"   - {pkg}")
        print(f"\nInstall with: pip install {' '.join(missing)}")
        return False
    
    return True


def clean_build_folders():
    """Remove build and dist folders."""
    folders = ['build', 'dist', '__pycache__']
    for folder in folders:
        if os.path.exists(folder):
            print(f"  Removing {folder}/")
            shutil.rmtree(folder)
    
    # Remove .spec files generated by pyinstaller (not our custom ones)
    for f in os.listdir('.'):
        if f.endswith('.spec') and f not in ['assignment-editor.spec', 'autograder.spec', 'autograder_build.spec']:
            print(f"  Removing {f}")
            os.remove(f)


def build_assignment_editor(debug=False):
    """Build the Assignment Editor executable."""
    spec_file = 'assignment-editor.spec'
    
    if not os.path.exists(spec_file):
        print(f"✗ {spec_file} not found!")
        print("   Please ensure assignment-editor.spec is in the current directory.")
        return False
    
    if not os.path.exists('assignment-editor-gui.py'):
        print("✗ assignment-editor-gui.py not found!")
        return False
    
    cmd = ['pyinstaller', '--clean', spec_file]
    
    return run_command(cmd, "Building Assignment Editor")


def build_autograder(debug=False):
    """Build the AutoGrader (student) executable."""
    # Check prerequisites
    if not os.path.exists('autograder-gui-app.py'):
        print("✗ autograder-gui-app.py not found!")
        return False
    
    if not os.path.exists('autograder.py'):
        print("✗ autograder.py not found!")
        return False
    
    if not os.path.exists('embedded_resources.py'):
        print("✗ embedded_resources.py not found!")
        print("   Run 'python encode_resources.py' first to embed config and assignments.")
        return False
    
    # Check for spec file (generated by Assignment Editor or use default)
    if os.path.exists('autograder_build.spec'):
        spec_file = 'autograder_build.spec'
        print("Using autograder_build.spec (generated by Assignment Editor)")
    elif os.path.exists('autograder.spec'):
        spec_file = 'autograder.spec'
        print("Using autograder.spec")
    else:
        print("✗ No spec file found!")
        print("   Either use Assignment Editor to generate one, or ensure")
        print("   autograder.spec is in the current directory.")
        return False
    
    cmd = ['pyinstaller', '--clean', spec_file]
    
    return run_command(cmd, "Building AutoGrader (Student App)")


def main():
    parser = argparse.ArgumentParser(
        description='Build AutoGrader executables',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__
    )
    parser.add_argument('--editor', action='store_true', help='Build only Assignment Editor')
    parser.add_argument('--grader', action='store_true', help='Build only AutoGrader')
    parser.add_argument('--all', action='store_true', help='Build both (default)')
    parser.add_argument('--clean', action='store_true', help='Clean build folders first')
    parser.add_argument('--debug', action='store_true', help='Build with console for debugging')
    
    args = parser.parse_args()
    
    # Default to building both if no specific option
    if not args.editor and not args.grader:
        args.all = True
    
    print("\n" + "="*60)
    print("  AutoGrader Build Script")
    print("="*60)
    
    # Check prerequisites
    if not check_prerequisites():
        sys.exit(1)
    
    # Clean if requested
    if args.clean:
        print("\nCleaning build folders...")
        clean_build_folders()
    
    results = []
    
    # Build Assignment Editor
    if args.editor or args.all:
        success = build_assignment_editor(debug=args.debug)
        results.append(('Assignment Editor', success))
    
    # Build AutoGrader
    if args.grader or args.all:
        success = build_autograder(debug=args.debug)
        results.append(('AutoGrader', success))
    
    # Summary
    print("\n" + "="*60)
    print("  BUILD SUMMARY")
    print("="*60)
    
    all_success = True
    for name, success in results:
        status = "✓ SUCCESS" if success else "✗ FAILED"
        print(f"  {name}: {status}")
        if not success:
            all_success = False
    
    if all_success:
        print("\n✓ All builds completed successfully!")
        print("\nOutput locations:")
        
        if sys.platform == 'darwin':
            print("  - dist/AssignmentEditor.app/")
            print("  - dist/AutoGrader.app/")
        elif sys.platform == 'win32':
            print("  - dist/AssignmentEditor.exe")
            print("  - dist/AutoGrader.exe")
        else:
            print("  - dist/AssignmentEditor")
            print("  - dist/AutoGrader")
        
        print("\nDistribution:")
        print("  1. Assignment Editor: Give to instructors for creating tests")
        print("  2. AutoGrader: Give to students for checking their code")
    else:
        print("\n✗ Some builds failed. Check the output above for details.")
        sys.exit(1)


if __name__ == '__main__':
    main()