"""
Encode config.ini and assignments.xlsx as base64 strings.
Run this BEFORE building the executable to embed files directly in the code.

Usage:
    python encode_resources.py
"""

import base64
import os

def encode_file(filepath):
    """Encode a file to base64 string"""
    if not os.path.exists(filepath):
        print(f"ERROR: {filepath} not found!")
        return None
    
    with open(filepath, 'rb') as f:
        encoded = base64.b64encode(f.read()).decode('utf-8')
    
    print(f"âœ“ Encoded {filepath} ({len(encoded)} characters)")
    return encoded

def main():
    print("Encoding resources for embedding...")
    print("="*60)
    
    # Encode files
    config_data = encode_file('config.ini')
    excel_data = encode_file('assignments.xlsx')
    
    if not config_data or not excel_data:
        print("\nERROR: Could not encode all files. Please check they exist.")
        return
    
    # Generate Python module
    output = f'''"""
Auto-generated embedded resources.
DO NOT EDIT MANUALLY!
Generated by encode_resources.py

This module contains config.ini and assignments.xlsx embedded as base64 strings.
Files are decoded at runtime and never extracted to disk in a visible location.
"""

import base64
import io
import tempfile
import os

# Embedded config.ini (base64 encoded)
CONFIG_DATA = """{config_data}"""

# Embedded assignments.xlsx (base64 encoded)
EXCEL_DATA = """{excel_data}"""

def get_config_string():
    """Return decoded config.ini content as string"""
    return base64.b64decode(CONFIG_DATA).decode('utf-8')

def get_excel_bytes():
    """Return decoded assignments.xlsx as bytes"""
    return base64.b64decode(EXCEL_DATA)

def get_excel_file():
    """Return path to temporary Excel file"""
    data = get_excel_bytes()
    
    # Create temporary file that will be cleaned up
    temp_file = tempfile.NamedTemporaryFile(delete=False, suffix='.xlsx', mode='wb')
    temp_file.write(data)
    temp_file.close()
    
    return temp_file.name

def get_config_parser():
    """Return ConfigParser object with embedded config"""
    import configparser
    config = configparser.ConfigParser()
    config.read_string(get_config_string())
    return config

def cleanup_temp_file(filepath):
    """Delete temporary file"""
    try:
        if filepath and os.path.exists(filepath):
            os.unlink(filepath)
    except:
        pass
'''
    
    # Write to file
    with open('embedded_resources.py', 'w', encoding='utf-8') as f:
        f.write(output)
    
    print("="*60)
    print("âœ“ Generated embedded_resources.py")
    print("\nEmbedded files:")
    print("  - config.ini")
    print("  - assignments.xlsx")
    print("\nThese files are now embedded in Python code!")
    print("\nNext steps:")
    print("  1. Verify embedded_resources.py was created")
    print("  2. Run: pyinstaller autograder.spec")
    print("  3. Test the executable in dist/ folder")
    print("\nThe executable will NOT contain separate config.ini or")
    print("assignments.xlsx files - they are compiled into the code!")

if __name__ == "__main__":
    main()